/** Sniper Chill economy. Vanilla ES module, no dependencies.
 * createEconomy({container,startingMoney=800,freezeTime=15,autoOpen=true,team='T',onEvent})
 * startRound(opts), update(dt seconds), endRound({won,reason}), recordKill({headshot,id}),
 * recordPlant(), recordDefuse(), buy(id), canBuy(id), damage(raw,{zone,armorPenetration}),
 * onDeath({position}), dropWeapon(id,{position}), pickupDrop(drop), setAmmo(id,ammo),
 * selectWeapon(id), consumeGrenade(id), getDefuseTime(), getState(), open/close/toggle,
 * on(event,callback)->unsubscribe, dispose(). mount:false supports headless testing.
 * Host MUST freeze movement/fire during phase=freeze or menuOpen; listen to phase/menu.
 * Host MUST gate weapon selection/shooting to inventory, sync ammo, place drop entities,
 * and implement grenade effects on 'grenade'. damage() returns healthDamage for host HP.
 * Inventory survives round starts, but death drops guns and clears gear. No reload persistence.
 * Events through onEvent(name,detail), on(name,fn), DOM economy:name on container.
 * Details carry detached state. Rewards/prices are CS-inspired chill tuning, not exact CS.
 */
export const WEAPON_ORDER=Object.freeze(['pistol','machinegun','sniper']);
export const WEAPON_STATS={
 pistol:{id:'pistol',name:'Chill Pistol',auto:false,rpm:360,mag:12,reserve:60,reloadTime:1.2,damage:{head:100,body:34,limb:20},range:80,pellets:1,spread:.004,spreadMove:.012,spreadPerShot:.004,spreadMax:.02,spreadRecover:6,recoil:{pitch:.014,yaw:.004,kick:.05,recover:10},zoom:1,scope:false,adsZoom:1.25,color:0x5ad1ff,flash:.8},
 machinegun:{id:'machinegun',name:'Chill-O-Matic',auto:true,rpm:780,mag:30,reserve:120,reloadTime:1.8,damage:{head:100,body:18,limb:11},range:70,pellets:1,spread:.007,spreadMove:.02,spreadPerShot:.0035,spreadMax:.05,spreadRecover:5,recoil:{pitch:.007,yaw:.005,kick:.04,recover:9},zoom:1,scope:false,adsZoom:1.3,color:0xffb347,flash:1},
 sniper:{id:'sniper',name:'Quiet Storm',auto:false,rpm:48,mag:5,reserve:20,reloadTime:2.6,damage:{head:200,body:100,limb:100},range:300,pellets:1,spread:.03,spreadMove:.06,spreadPerShot:0,spreadMax:.06,spreadRecover:4,adsSpread:0,recoil:{pitch:.05,yaw:.008,kick:.12,recover:5},zoom:4,scope:true,adsZoom:4,color:0x9affc4,flash:1.3}
};
export const REWARDS={kill:300,headshot:150,win:3250,loss:1400,lossStep:500,lossMax:3400,plant:300,defuse:300,plantLoss:800};
export const MAX_MONEY=16000;
export const ITEMS={
 pistol:{name:'Chill Pistol',price:200,category:0,slot:'secondary',desc:'12 rounds · quick reload · crisp headshots'},
 machinegun:{name:'Chill-O-Matic',price:1800,category:1,slot:'primary',desc:'30 rounds · full auto · close-range chaos'},
 sniper:{name:'Quiet Storm',price:3500,category:2,slot:'primary',desc:'5 rounds · 4× scope · one-tap power'},
 armor:{name:'Cloud Shield',price:650,category:3,desc:'100 armor · absorbs 50% of body damage'},
 helmet:{name:'Bucket of Calm',price:350,category:3,desc:'Extends armor protection to headshots'},
 knifeskin:{name:'Kite Cutter',price:300,category:3,desc:'Pastel kite knife skin · shiny, quiet, extra stylish'},
 defusekit:{name:'Easy-Off Kit',price:400,category:3,desc:'CT only · defuse in 5s instead of 10s'},
 frag:{name:'Spicy Pebble',price:300,category:4,desc:'Frag grenade · max 1'},
 smoke:{name:'Pocket Cloud',price:300,category:4,desc:'Smoke grenade · max 1'},
 flash:{name:'Disco Blink',price:200,category:4,desc:'Flash grenade · max 2'}
};
const cats=['PISTOLS','MACHINE GUNS','SNIPERS','GEAR','GRENADES'];
const copy=v=>JSON.parse(JSON.stringify(v)), clamp=(n,a,b)=>Math.max(a,Math.min(b,n)), finite=n=>typeof n==='number'&&Number.isFinite(n), cash=n=>'$'+Math.round(n).toLocaleString('en-US');
const ammo=id=>({mag:WEAPON_STATS[id].mag,reserve:WEAPON_STATS[id].reserve});
const empty=()=>({primary:null,secondary:null,ammo:{},armor:0,helmet:false,defusekit:false,knifeskin:false,grenades:{frag:0,smoke:0,flash:0}});
export function createEconomy(o={}){
 const root=o.container||(typeof document!=='undefined'?document.body:null),reward={...REWARDS,...o.rewards};
 let remoteBuy=null,disposed=false,ui=null,serial=0,notice='',noticeLeft=0;const listeners=new Map(),kills=new Set(),picked=new Set();
 const s={money:clamp(Math.floor(finite(o.startingMoney)?o.startingMoney:800),0,MAX_MONEY),round:0,team:o.team==='CT'?'CT':'T',phase:'idle',freezeRemaining:0,alive:true,lossStreak:0,roundSettled:false,menuOpen:false,activeWeapon:'pistol',inventory:empty(),planted:false,defused:false};
 s.inventory.secondary='pistol';s.inventory.ammo.pistol=ammo('pistol');
 const getState=()=>copy(s),render=()=>ui?.render();
 function emit(name,data={}){const payload={...copy(data),state:getState()};const call=fn=>{try{fn(copy(payload))}catch(e){console.error('[economy]',e)}};if(o.onEvent)call(p=>o.onEvent(name,p));for(const fn of listeners.get(name)||[])call(fn);if(root&&typeof CustomEvent!=='undefined')root.dispatchEvent(new CustomEvent('economy:'+name,{detail:payload}));}
 function funds(n,reason){const before=s.money;s.money=clamp(Math.floor(s.money+n),0,MAX_MONEY);emit('money',{amount:s.money-before,reason});render();return s.money-before;}
 function shopOk(){return (s.phase==='freeze'&&s.freezeRemaining>0)||(s.phase==='live'&&!!o.inZone&&!!o.inZone());}
 function menu(open){if(disposed)return false;if(open&&(!s.alive||!shopOk()))return false;if(s.menuOpen===!!open)return true;s.menuOpen=!!open;emit('menu',{open:s.menuOpen,blocksInput:s.menuOpen});render();ui?.focus(open);return true;}
 function canBuy(id){const i=ITEMS[id],v=s.inventory;let reason='';if(disposed)reason='Shop closed';else if(!i)reason='Unknown item';else if(!s.alive)reason='Back next round';else if(!shopOk())reason='Buy time is over';else if(id==='defusekit'&&s.team!=='CT')reason='CT team only';else if(i.slot&&v[i.slot]===id)reason='Already equipped';else if(id==='armor'&&v.armor>=100)reason='Shield is full';else if(['helmet','defusekit','knifeskin'].includes(id)&&v[id])reason='Already owned';else if(i.category===4&&(v.grenades[id]>=(id==='flash'?2:1)||Object.values(v.grenades).reduce((a,b)=>a+b,0)>=4))reason='Grenade limit reached';else if(s.money<i.price)reason='Need '+cash(i.price-s.money)+' more';return {ok:!reason,reason};}
 function dropWeapon(id,{position=null,reason='manual'}={}){if(disposed||!WEAPON_STATS[id])return null;const v=s.inventory,slot=ITEMS[id].slot;if(v[slot]!==id)return null;const drop={dropId:`r${s.round}-d${++serial}`,weapon:id,ammo:copy(v.ammo[id]),position:position?copy(position):null};v[slot]=null;delete v.ammo[id];if(s.activeWeapon===id)s.activeWeapon=v.primary||v.secondary||null;emit('drop',{drop,reason});emit('inventory');emit('equip',{weapon:s.activeWeapon});render();return drop;}
 function buy(id){const c=canBuy(id);if(!c.ok){notice=c.reason;noticeLeft=3;emit('denied',{id,reason:c.reason});render();return c;}if(remoteBuy){remoteBuy(id);return {ok:true,pending:true};}const i=ITEMS[id],v=s.inventory;const replacedDrop=i.slot&&v[i.slot]?dropWeapon(v[i.slot],{reason:'replacement'}):null;if(i.slot){v[i.slot]=id;v.ammo[id]=ammo(id);s.activeWeapon=id;}else if(id==='armor')v.armor=100;else if(['helmet','defusekit','knifeskin'].includes(id))v[id]=true;else v.grenades[id]++;funds(-i.price,'buy:'+id);emit('purchase',{id,price:i.price,replacedDrop});emit('inventory');if(i.slot)emit('equip',{weapon:id});notice=i.name+' is yours. Stay chill.';noticeLeft=3;render();return {ok:true,id,replacedDrop};}
 function startRound({team=s.team,freezeTime=o.freezeTime??15,autoOpen=o.autoOpen??true}={}){if(disposed)return false;menu(false);s.round++;s.team=team==='CT'?'CT':'T';s.alive=true;s.roundSettled=false;s.planted=s.defused=false;kills.clear();notice='';if(s.team!=='CT')s.inventory.defusekit=false;if(!s.inventory.secondary){s.inventory.secondary='pistol';s.inventory.ammo.pistol=ammo('pistol');}s.activeWeapon=s.inventory.primary||s.inventory.secondary;s.freezeRemaining=finite(freezeTime)?Math.max(0,freezeTime):15;s.phase=s.freezeRemaining>0?'freeze':'live';ui?.category(0);emit('round-start',{round:s.round});emit('inventory');emit('equip',{weapon:s.activeWeapon});emit('phase',{phase:s.phase,blocksInput:s.phase==='freeze'});if(autoOpen)menu(true);render();return true;}
 function endRound({won=false,reason='elimination'}={}){if(disposed||!s.round||s.roundSettled)return {ok:false};s.roundSettled=true;menu(false);s.phase='ended';s.freezeRemaining=0;let amount;if(won){amount=reward.win;s.lossStreak=Math.max(0,s.lossStreak-1);}else{amount=Math.min(reward.lossMax,reward.loss+s.lossStreak*reward.lossStep);s.lossStreak++;if(s.team==='T'&&s.planted)amount+=reward.plantLoss;}const paid=funds(amount,won?'round-win':'round-loss');emit('round-end',{won,reason,award:paid});emit('phase',{phase:'ended',blocksInput:true});render();return {ok:true,award:paid};}
 function recordKill({headshot=false,id,weapon=s.activeWeapon}={}){if(disposed||s.phase!=='live'||!s.alive)return 0;if(id!==undefined){if(kills.has(String(id)))return 0;kills.add(String(id));}const amount=funds(reward.kill+(headshot?reward.headshot:0),headshot?'headshot':'kill');emit('reward',{kind:headshot?'headshot':'kill',amount,weapon});return amount;}
 function objective(kind){const flag=kind==='plant'?'planted':'defused';if(disposed||s.phase!=='live'||!s.alive||s[flag]||s.team!==(kind==='plant'?'T':'CT'))return 0;s[flag]=true;const amount=funds(reward[kind],kind);emit('objective',{kind,amount});return amount;}
 function setAmmo(id,a){if(disposed||!s.inventory.ammo[id]||!a)return false;for(const key of ['mag','reserve'])if(finite(a[key]))s.inventory.ammo[id][key]=clamp(Math.floor(a[key]),0,WEAPON_STATS[id][key]);return true;}
 function onDeath({position=null}={}){if(disposed||!s.alive)return [];s.alive=false;menu(false);const drops=[s.inventory.primary,s.inventory.secondary].filter(Boolean).map(id=>dropWeapon(id,{position,reason:'death'}));s.inventory=empty();s.activeWeapon=null;emit('inventory');emit('death',{drops});render();return drops;}
 function pickupDrop(drop){if(disposed||!s.alive||s.phase!=='live')return {ok:false,reason:'Cannot pick up now'};if(!drop||!WEAPON_STATS[drop.weapon]||!drop.dropId)return {ok:false,reason:'Invalid drop'};if(picked.has(drop.dropId))return {ok:false,reason:'Already picked up'};const id=drop.weapon,slot=ITEMS[id].slot;const replacedDrop=s.inventory[slot]?dropWeapon(s.inventory[slot],{position:drop.position,reason:'pickup-replacement'}):null;s.inventory[slot]=id;s.inventory.ammo[id]=ammo(id);setAmmo(id,drop.ammo);s.activeWeapon=id;picked.add(drop.dropId);emit('pickup',{dropId:drop.dropId,weapon:id,replacedDrop});emit('inventory');emit('equip',{weapon:id});render();return {ok:true,replacedDrop};}
 function damage(n,{zone='body',armorPenetration=0}={}){if(disposed||!s.alive||!finite(n)||n<=0)return {healthDamage:0,absorbed:0,armor:s.inventory.armor};const pen=finite(armorPenetration)?clamp(armorPenetration,0,1):0,v=s.inventory;const absorbed=zone!=='head'||v.helmet?Math.min(v.armor,n*.5*(1-pen)):0;v.armor-=absorbed;const result={healthDamage:n-absorbed,absorbed,armor:v.armor};emit('damage',{...result,zone});render();return result;}
 function remote(st){if(disposed||!st)return;const v=s.inventory;if(finite(st.money))s.money=clamp(Math.floor(st.money),0,MAX_MONEY);if('primary' in st){if(st.primary&&!v.ammo[st.primary])v.ammo[st.primary]=ammo(st.primary);v.primary=st.primary||null;}if('secondary' in st){if(st.secondary&&!v.ammo[st.secondary])v.ammo[st.secondary]=ammo(st.secondary);v.secondary=st.secondary||null;}if(st.team)s.team=st.team==='CT'?'CT':'T';if('alive' in st)s.alive=!!st.alive;if(st.phase){s.phase=st.phase;s.freezeRemaining=finite(st.freezeRemaining)?st.freezeRemaining:0;if(st.phase!=='freeze'&&s.menuOpen){s.menuOpen=false;emit('menu',{open:false,blocksInput:false});}}render();}
 const api={remote,setRemote:fn=>{remoteBuy=typeof fn==='function'?fn:null;},canShop:()=>!disposed&&s.alive&&shopOk(),getState,canBuy,buy,startRound,endRound,recordKill,recordPlant:()=>objective('plant'),recordDefuse:()=>objective('defuse'),damage,onDeath,dropWeapon,pickupDrop,setAmmo,open:()=>menu(true),close:()=>menu(false),toggle:()=>menu(!s.menuOpen),getDefuseTime:()=>s.inventory.defusekit?5:10,
 on(name,fn){if(typeof fn!=='function')throw new TypeError('Callback required');if(!listeners.has(name))listeners.set(name,new Set());listeners.get(name).add(fn);return()=>listeners.get(name)?.delete(fn);},
 update(dt){if(disposed||!finite(dt)||dt<=0)return;if(s.phase==='freeze'){s.freezeRemaining=Math.max(0,s.freezeRemaining-dt);if(!s.freezeRemaining){menu(false);s.phase='live';emit('phase',{phase:'live',blocksInput:false});}}if(noticeLeft>0){noticeLeft=Math.max(0,noticeLeft-dt);if(!noticeLeft)notice='';}render();},
 selectWeapon(id){if(disposed||!s.alive||!id||![s.inventory.primary,s.inventory.secondary].includes(id))return false;s.activeWeapon=id;emit('equip',{weapon:id});render();return true;},
 consumeGrenade(id){if(disposed||!s.alive||s.phase!=='live'||!(s.inventory.grenades[id]>0))return false;s.inventory.grenades[id]--;emit('grenade',{id});emit('inventory');render();return true;},
 dispose(){if(disposed)return;menu(false);disposed=true;ui?.dispose();listeners.clear();}};
 if(o.mount!==false&&root&&typeof document!=='undefined')ui=mountUI(root,api,()=>notice);render();return api;
}
export default createEconomy;
const ICONS={knifeskin:'M10 62L50 14l10 8-34 42z M44 12l14-4 6 14 M12 66l8-4',pistol:'M12 28h43v10H33l-4 22H17l5-22H12z',machinegun:'M6 30h54v12H38l-5 19H21l5-19H6z M60 34h12 M17 30V17h15v13',sniper:'M5 35h49v9H28l-5 14H10l5-14H5z M54 37h20 M28 33V22h22v8H28 M58 44l8 14',armor:'M38 11l23 10v19c0 15-23 25-23 25S15 55 15 40V21z M26 38l8 8 17-18',helmet:'M14 43V34a24 24 0 0148 0v9H14z M62 43v15H44V43',defusekit:'M16 24h44v34H16z M28 24V13h20v11 M38 33v16 M30 41h16',frag:'M30 24V13h16v11 M44 13h14l6 16 M38 24a19 21 0 110 42 19 21 0 010-42 M21 36h34 M20 47h36 M31 26v36 M44 26v36',smoke:'M26 27h24v36H26z M32 27V15h12v12 M31 43h14 M29 8c-10-12 16-13 9-3 M47 10c12-12-1-20-7-16',flash:'M28 27h21v35H28z M34 27V16h10v11 M38 4v6 M16 19l7 4 M59 18l-7 5 M14 41h9 M56 40h8'};
const CSS=`
.sc-economy{--mint:#b7f7c7;--gold:#ffda87;position:absolute;inset:0;z-index:250;pointer-events:none;color:#f0f6f5;font-family:Fredoka,Inter,system-ui,sans-serif;font-variant-numeric:tabular-nums}.sc-economy *{box-sizing:border-box}.sc-economy [hidden]{display:none!important}.sc-economy button{font:inherit;cursor:pointer}.sc-economy button:focus-visible{outline:3px solid var(--gold);outline-offset:3px}.sc-economy kbd{font:700 10px monospace;display:inline-block;border:1px solid #bdd0c34d;padding:3px 6px;border-radius:5px;color:#d4e1da}
.sc-economy .eco-chip{position:absolute;right:12px;top:12px;pointer-events:auto;background:#101b20eb;border:1px solid #9cd9b655;border-radius:15px;color:var(--mint);padding:8px 18px;display:flex;gap:0;align-items:center}.sc-economy .eco-chip strong{font-size:24px}.sc-economy .eco-chip span{display:none;font-size:11px;letter-spacing:.07em;color:#c0d3c6}
.sc-economy .eco-shade{position:absolute;inset:0;pointer-events:auto;display:flex;align-items:center;justify-content:center;padding:24px;background:linear-gradient(115deg,#0c1820f2,#192f2beb);backdrop-filter:blur(8px)}.sc-economy .eco-panel{width:min(1080px,100%);max-height:100%;overflow:auto;padding:28px;border:1px solid #d4e8dc27;border-radius:26px;background:linear-gradient(145deg,#263b36,#111e23);box-shadow:0 24px 100px #0007}.sc-economy .eco-top{display:flex;align-items:center;justify-content:space-between;gap:20px;padding-bottom:22px;border-bottom:1px solid #b5dcc523}.sc-economy .eco-eyebrow{font-size:11px;letter-spacing:.18em;font-weight:800;color:var(--mint)}.sc-economy h2{font-size:32px;letter-spacing:-.04em;margin:5px 0}.sc-economy .eco-sub{font-size:13px;color:#b3c3b9}.sc-economy .eco-bank{display:flex;gap:20px;align-items:center}.sc-economy .eco-cash{text-align:right}.sc-economy .eco-cash small{display:block;color:#a7bdb2;font-size:10px;letter-spacing:.15em}.sc-economy .eco-cash strong{font-size:34px;color:var(--mint)}.sc-economy .eco-clock{padding:10px 16px;background:#ffda8714;border:1px solid #ffda8733;border-radius:14px;min-width:90px;text-align:center;color:var(--gold)}.sc-economy .eco-clock small{display:block;font-size:9px;letter-spacing:.08em}.sc-economy .eco-clock b{font-size:25px}
.sc-economy .eco-main{display:grid;grid-template-columns:390px 1fr;gap:38px;align-items:center;padding:24px 0}.sc-economy .eco-wheel{width:370px;height:370px;position:relative;margin:auto;max-width:100%}.sc-economy .eco-wheel svg{width:100%;height:100%;filter:drop-shadow(0 12px 22px #0003)}.sc-economy .eco-wheel path{fill:#ffffff08;stroke:#adcdbd26;stroke-width:1;cursor:pointer}.sc-economy .eco-wheel path.active{fill:#b7f7c729;stroke:#b7f7c787}.sc-economy .eco-wheel button{position:absolute;transform:translate(-50%,-50%);background:none;border:0;color:#b2c7bb;width:105px;min-height:54px;font-size:10px;font-weight:800;letter-spacing:.06em;line-height:1.4}.sc-economy .eco-wheel button.active{color:var(--mint)}.sc-economy .eco-wheel kbd{display:block;width:22px;margin:0 auto 6px}.sc-economy .eco-center{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:128px;height:128px;border-radius:50%;border:1px solid #b7f7c744;background:#182b2c;display:flex;align-items:center;justify-content:center;flex-direction:column;box-shadow:0 0 0 7px #111e2355}.sc-economy .eco-center b{font-size:27px;color:var(--gold)}.sc-economy .eco-center span{font-size:10px;letter-spacing:.1em;color:#a4b9ae;margin-top:5px}.sc-economy .eco-section{font-size:11px;color:#b1c7bb;letter-spacing:.15em;font-weight:800;margin-bottom:12px}.sc-economy .eco-cards{display:grid;gap:10px}.sc-economy .eco-card{display:grid;grid-template-columns:76px 1fr auto;align-items:center;gap:14px;width:100%;text-align:left;min-height:110px;border:1px solid #bfdcc82b;border-radius:17px;padding:17px;background:#07131832;color:#f0f6f5}.sc-economy .eco-card:hover:not(:disabled){border-color:var(--mint);background:#b7f7c710}.sc-economy .eco-card:disabled{cursor:default}.sc-economy .eco-card:disabled svg{opacity:.45}.sc-economy .eco-card svg{width:70px;height:70px;color:var(--gold)}.sc-economy .eco-card strong{display:block;font-size:18px;letter-spacing:-.02em}.sc-economy .eco-card small{display:block;font-size:11px;color:#a1bbae;margin-top:8px;line-height:1.6}.sc-economy .eco-price{font-size:20px;font-weight:800;text-align:right;color:var(--mint);white-space:nowrap}.sc-economy .eco-price small{font-size:10px;max-width:110px;white-space:normal}.sc-economy .eco-price kbd{margin-top:8px}.sc-economy .eco-card:disabled .eco-price{color:#9aac9f}.sc-economy .eco-footer{border-top:1px solid #b5dcc523;padding-top:18px;display:flex;justify-content:space-between;align-items:center;gap:16px}.sc-economy .eco-loadout{font-size:11px;color:#b4cabb;line-height:1.8}.sc-economy .eco-ready{border:0;border-radius:12px;padding:13px 20px;background:var(--mint);color:#153626;font-weight:800;white-space:nowrap}.sc-economy .eco-ready kbd{color:#153626;border-color:#15362655}.sc-economy .eco-note{font-size:12px;color:var(--gold);min-height:18px;margin-top:14px}
@media(max-width:850px){.sc-economy .eco-main{grid-template-columns:280px 1fr;gap:16px}.sc-economy .eco-wheel{width:270px;height:270px}.sc-economy .eco-center{width:90px;height:90px}.sc-economy .eco-wheel button{width:80px;font-size:8px}.sc-economy .eco-card{grid-template-columns:48px 1fr auto;padding:12px;gap:10px}.sc-economy .eco-card svg{width:48px;height:48px}.sc-economy .eco-card strong{font-size:15px}.sc-economy .eco-price{font-size:16px}.sc-economy .eco-panel{padding:20px}}
@media(max-width:620px){.sc-economy .eco-shade{padding:10px}.sc-economy .eco-panel{padding:17px;border-radius:20px}.sc-economy .eco-main{grid-template-columns:1fr;padding:12px 0;gap:14px}.sc-economy .eco-wheel{width:230px;height:230px}.sc-economy .eco-top{align-items:flex-start;gap:10px;padding-bottom:12px}.sc-economy h2{font-size:24px}.sc-economy .eco-bank{gap:8px}.sc-economy .eco-cash strong{font-size:23px}.sc-economy .eco-clock{padding:7px;min-width:54px}.sc-economy .eco-clock b{font-size:20px}.sc-economy .eco-eyebrow{font-size:8px}.sc-economy .eco-sub{font-size:11px;max-width:180px}.sc-economy .eco-card{min-height:92px}.sc-economy .eco-ready{padding:11px;font-size:11px}.sc-economy .eco-note{font-size:11px}.sc-economy .eco-chip{right:8px;top:8px}}
`;
function mountUI(root,api,getNotice){
 const doc=root.ownerDocument,style=doc.createElement('style');style.textContent=CSS;doc.head.appendChild(style);const el=doc.createElement('div');el.className='sc-economy';el.innerHTML=`<button class="eco-chip" aria-label="Open buy menu"><strong></strong><span></span></button><div class="eco-shade" hidden><section class="eco-panel" role="dialog" aria-modal="true" aria-label="Buy menu" tabindex="-1"><header class="eco-top"><div><div class="eco-eyebrow">CHILLOPS / FIELD SUPPLIES</div><h2>Buy smart. Play chill.</h2><div class="eco-sub">A fresh round. A fresh little plan.</div></div><div class="eco-bank"><div class="eco-cash"><small>YOUR WALLET</small><strong></strong></div><div class="eco-clock"><small>BUY TIME</small><b></b></div></div></header><div class="eco-main"><nav class="eco-wheel" aria-label="Buy categories"><svg viewBox="0 0 370 370"></svg><div class="eco-center"><b>CHILL</b><span></span></div></nav><div><div class="eco-section"></div><div class="eco-cards"></div></div></div><footer class="eco-footer"><div class="eco-loadout"></div><button class="eco-ready">LET'S GO <kbd>B</kbd></button></footer><div class="eco-note" role="status" aria-live="polite"></div></section></div>`;root.appendChild(el);
 const $=q=>el.querySelector(q),wheel=$('.eco-wheel'),svg=$('.eco-wheel svg'),cards=$('.eco-cards'),panel=$('.eco-panel');let cat=0,level='cats',signature='',before=null;
 const point=(r,d)=>[185+r*Math.cos(d*Math.PI/180),185+r*Math.sin(d*Math.PI/180)];
 cats.forEach((label,i)=>{const start=-124+i*72,end=start+68,a=point(176,start),b=point(176,end),c=point(78,end),d=point(78,start),p=doc.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',`M${a}A176 176 0 0 1 ${b}L${c}A78 78 0 0 0 ${d}Z`);p.dataset.cat=i;p.onclick=()=>{cat=i;render()};svg.appendChild(p);const xy=point(128,(start+end)/2),btn=doc.createElement('button');btn.dataset.cat=i;btn.style.left=xy[0]/370*100+'%';btn.style.top=xy[1]/370*100+'%';btn.innerHTML=`<kbd>${i+1}</kbd>${label}`;btn.onclick=()=>{cat=i;render()};wheel.appendChild(btn);});
 $('.eco-ready').onclick=()=>api.close();$('.eco-chip').onclick=()=>api.toggle();
 const stop=e=>e.stopPropagation();['pointerdown','mousedown','mouseup','click','wheel','contextmenu'].forEach(type=>el.addEventListener(type,stop));
 const keydown=e=>{if(e.target.matches?.('input,textarea,select,[contenteditable="true"]'))return;const s=api.getState();if(e.code==='KeyB'&&(s.phase==='freeze'||s.phase==='live')&&!e.repeat&&(!s.menuOpen&&api.canShop())){e.preventDefault();e.stopImmediatePropagation();api.toggle();return;}if(!s.menuOpen)return;if(e.code==='Enter'||e.code==='NumpadEnter'){e.preventDefault();e.stopImmediatePropagation();const rb=el.querySelector('.eco-ready');if(rb&&!rb.disabled)rb.click();return;}e.stopImmediatePropagation();if(e.code==='Escape'||e.code==='KeyB'){e.preventDefault();if(level==='items'){level='cats';signature='';render();}else api.close();return;}if(e.repeat)return;const n=Number(e.code.replace('Digit',''));if(n>=1&&n<=9){e.preventDefault();if(level==='cats'){if(n<=cats.length){cat=n-1;level='items';signature='';render();}}else{const id=Object.keys(ITEMS).filter(id=>ITEMS[id].category===cat)[n-1];if(id)api.buy(id);}return;}if(e.code==='Tab'){const fs=[...panel.querySelectorAll('button:not(:disabled)')],i=fs.indexOf(doc.activeElement);e.preventDefault();fs[(i+(e.shiftKey?-1:1)+fs.length)%fs.length]?.focus();}};
 doc.addEventListener('keydown',keydown,true);
 function render(){const s=api.getState(),v=s.inventory;if(!s.menuOpen&&level!=='cats'){level='cats';signature='';}$('.eco-shade').hidden=!s.menuOpen;$('.eco-chip').hidden=['idle','ended'].includes(s.phase);$('.eco-chip').disabled=s.phase!=='freeze'||!s.alive;$('.eco-chip strong').textContent=cash(s.money);$('.eco-chip span').textContent='';$('.eco-cash strong').textContent=cash(s.money);$('.eco-clock b').textContent=Math.ceil(s.freezeRemaining)+'s';$('.eco-center span').textContent=`${s.team} · ROUND ${s.round}`;$('.eco-section').textContent=cats[cat]+' / CHOOSE YOUR VIBE';$('.eco-note').textContent=getNotice()||(level==='cats'?'Press 1-5 to open a category · Esc or B closes the shop':'Press a number to buy · Esc or B goes back to categories');$('.eco-loadout').textContent=`LOADOUT · ${v.primary?ITEMS[v.primary].name:'No primary'} · ${v.secondary?ITEMS[v.secondary].name:'No sidearm'}\nShield ${Math.ceil(v.armor)} · Helmet ${v.helmet?'on':'off'} · Kit ${v.defusekit?'yes':'no'} · Grenades ${Object.values(v.grenades).reduce((a,b)=>a+b,0)}/4`;$('.eco-loadout').style.whiteSpace='pre-line';wheel.querySelectorAll('[data-cat]').forEach(e=>{e.classList.toggle('active',Number(e.dataset.cat)===cat);if(e.tagName==='BUTTON')e.setAttribute('aria-pressed',String(Number(e.dataset.cat)===cat));});const sig=JSON.stringify([level,cat,s.money,v,s.phase,s.alive,s.team]);if(sig===signature)return;signature=sig;const focused=doc.activeElement?.dataset?.item;cards.replaceChildren();Object.keys(ITEMS).filter(id=>ITEMS[id].category===cat).forEach((id,index)=>{const item=ITEMS[id],check=api.canBuy(id),btn=doc.createElement('button');btn.className='eco-card';btn.dataset.item=id;btn.disabled=!check.ok;btn.setAttribute('aria-label',`${item.name}, ${cash(item.price)}, ${check.ok?'buy':check.reason}`);btn.innerHTML=`<svg viewBox="0 0 76 76" fill="none" stroke="currentColor" stroke-width="3" stroke-linejoin="round" stroke-linecap="round" aria-hidden="true"><path d="${ICONS[id]}"/></svg><div><strong>${item.name}</strong><small>${item.desc}</small></div><div class="eco-price">${cash(item.price)}<small>${check.ok?'BUY':check.reason}</small><kbd>${level==='items'?index+1:''}</kbd></div>`;btn.onclick=()=>api.buy(id);cards.appendChild(btn);});if(focused){const target=cards.querySelector(`[data-item="${focused}"]`);if(target&&!target.disabled)target.focus();else $('.eco-ready').focus();}}
 return {render,category(n){cat=n;},focus(open){if(open){before=doc.activeElement;panel.focus()}else if(before?.isConnected)before.focus()},dispose(){doc.removeEventListener('keydown',keydown,true);el.remove();style.remove()}};
}
